# Generated by Django 5.0.6 on 2024-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Имел/Имеет платную подписку'),
        ),
    ]
