# Generated by Django 5.0.8 on 2024-10-09 14:25

import api.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_users_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serail',
            options={'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.AddField(
            model_name='comments',
            name='serail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.serail'),
        ),
        migrations.AlterField(
            model_name='serail',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serails', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='serail',
            name='vertical_photo',
            field=models.ImageField(blank=True, null=True, storage=api.storage_backends.PhotoStorage(), upload_to='serail/', verbose_name='Вертикальная обложка'),
        ),
        migrations.AlterField(
            model_name='series',
            name='video',
            field=models.FileField(storage=api.storage_backends.VideoStorage(), upload_to='series/'),
        ),
        migrations.AlterField(
            model_name='statusnew',
            name='serail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statusnew', to='api.serail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, storage=api.storage_backends.PhotoStorage(), upload_to='static/media/users/', verbose_name='Аватарка пользователя'),
        ),
        migrations.CreateModel(
            name='ViewedSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'unique_together': {('user', 'series')},
            },
        ),
    ]
