# Generated by Django 5.0.8 on 2024-10-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_serail_options_comments_serail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='search_history',
            field=models.JSONField(default=list, verbose_name='История поиска'),
        ),
    ]
