# Generated by Django 5.0.8 on 2024-10-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_docstexts'),
    ]

    operations = [
        migrations.AddField(
            model_name='serail',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.language'),
        ),
    ]
