# Generated by Django 5.0.8 on 2024-10-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_serail_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='serail',
            name='is_original',
            field=models.BooleanField(default=False, verbose_name='Является оригиналом'),
        ),
        migrations.AddField(
            model_name='serail',
            name='views',
            field=models.BigIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
