# Generated by Django 5.0.8 on 2024-10-12 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_serail_is_original_serail_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusnew',
            name='added_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления статуса'),
            preserve_default=False,
        ),
    ]
