# Generated by Django 5.0.8 on 2024-10-17 12:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_statusnew_added_date'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='docstexts',
            name='name',
            field=models.CharField(choices=[('TERMS_OF_USE', 'TERMS_OF_USE'), ('PRIVACY_POLICY', 'PRIVACY_POLICY'), ('DMCA', 'DMCA')], max_length=250, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.serail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
    ]
