# Generated by Django 5.0.8 on 2024-10-21 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_payments_done_date_alter_docstexts_name_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serail',
            name='vertical_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/serail/', verbose_name='Вертикальная обложка'),
        ),
        migrations.CreateModel(
            name='PermissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
            },
        ),
    ]
