# Generated by Django 5.0.8 on 2024-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_serail_vertical_photo_permissionsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/media/users/', verbose_name='Аватарка пользователя'),
        ),
    ]
