# Generated by Django 5.0.8 on 2024-10-24 08:19

import django.utils.timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('TEMPORARILY', 'TEMPORARILY'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], default=1988, max_length=250, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
