# Generated by Django 5.0.8 on 2024-10-25 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payments_created_date_payments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], max_length=300, verbose_name='Тип подписки')),
                ('price', models.CharField(default=0, max_length=300, verbose_name='Цена')),
                ('percent', models.CharField(default='0', max_length=250, verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.AlterModelOptions(
            name='viewedseries',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Просмотры'},
        ),
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=250, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], max_length=250, verbose_name='Тип'),
        ),
    ]
