# Generated by Django 5.0.8 on 2024-10-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subscriptions_alter_viewedseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birthday',
            field=models.CharField(max_length=250, null=True, verbose_name='Дата рождения'),
        ),
    ]
