# Generated by Django 5.0.8 on 2024-10-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subscriptions_alter_viewedseries_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('date', models.DateField(verbose_name='День праздника')),
                ('percent', models.CharField(default='0', max_length=300, verbose_name='Процент скидки')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздник',
            },
        ),
    ]
