# Generated by Django 5.0.8 on 2024-10-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_users_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='percent',
            field=models.CharField(default='0', max_length=250, verbose_name='Скидка'),
        ),
    ]
