# Generated by Django 5.0.8 on 2024-10-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_newprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasts',
            name='stars_percent',
            field=models.CharField(default='0', max_length=300, verbose_name='Скидка для tg stars'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='stars_percent',
            field=models.CharField(default='0', max_length=250, verbose_name='Скидка для tg stars'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='stars_price',
            field=models.CharField(default='', max_length=300, verbose_name='Цена в tg stars'),
        ),
        migrations.AlterField(
            model_name='serail',
            name='rating',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='percent',
            field=models.CharField(default='0', max_length=250, verbose_name='Скидка для рубля'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='price',
            field=models.CharField(default='0', max_length=300, verbose_name='Цена в руб'),
        ),
    ]
