# Generated by Django 5.0.8 on 2024-10-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_feasts_stars_percent_subscriptions_stars_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('TEMPORARILY_WEEK', 'TEMPORARILY_WEEK'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], max_length=250, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='subtype',
            field=models.CharField(choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('TEMPORARILY_WEEK', 'TEMPORARILY_WEEK'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], max_length=300, verbose_name='Тип подписки'),
        ),
    ]
