# Generated by Django 5.0.8 on 2024-10-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_payments_status_alter_subscriptions_subtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newprice',
            name='month',
        ),
        migrations.RemoveField(
            model_name='newprice',
            name='year',
        ),
        migrations.AddField(
            model_name='newprice',
            name='periodtype',
            field=models.CharField(choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('TEMPORARILY_WEEK', 'TEMPORARILY_WEEK')], default=2000, max_length=300, verbose_name='Тип периода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newprice',
            name='price',
            field=models.CharField(default='0', max_length=300, verbose_name='Цена в руб'),
        ),
        migrations.AddField(
            model_name='newprice',
            name='stars_price',
            field=models.CharField(default='', max_length=300, verbose_name='Цена в tg stars'),
        ),
    ]
