# Generated by Django 5.0.8 on 2024-10-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_newprice_month_remove_newprice_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprice',
            name='stars_price',
            field=models.CharField(default='0', max_length=300, verbose_name='Цена в tg stars'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='stars_price',
            field=models.CharField(default='0', max_length=300, verbose_name='Цена в tg stars'),
        ),
        migrations.CreateModel(
            name='SerailPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(default='0', max_length=300, verbose_name='Цена в руб')),
                ('stars_price', models.CharField(default='0', max_length=300, verbose_name='Цена в tg stars')),
                ('serail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serail')),
            ],
            options={
                'verbose_name': 'Цена на сериал',
                'verbose_name_plural': 'Цены на сериалы',
            },
        ),
    ]
