# Generated by Django 5.0.8 on 2024-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_newprice_stars_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serail',
            name='likes',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Лайки'),
        ),
    ]
