# Generated by Django 5.0.8 on 2024-10-31 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_history_serail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.language'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.AlterField(
            model_name='serail',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serails', to='api.genre'),
        ),
        migrations.AlterField(
            model_name='statusnew',
            name='serail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statusnew', to='api.serail'),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.country'),
        ),
        migrations.AlterField(
            model_name='users',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.language'),
        ),
    ]
