# Generated by Django 5.0.8 on 2024-10-31 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='sub',
            field=models.ForeignKey(default=11.0, on_delete=django.db.models.deletion.PROTECT, to='api.subscriptions'),
            preserve_default=False,
        ),
    ]
