# Generated by Django 5.0.8 on 2024-10-31 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tokens_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='sub',
        ),
    ]
