# Generated by Django 5.0.8 on 2024-11-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_users_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.CharField(max_length=300, verbose_name='TG ID')),
                ('data', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
