# Generated by Django 5.0.8 on 2024-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_serail_horizontal_photo0_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForBirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionid', models.BigIntegerField(verbose_name='ID доступа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
