# Generated by Django 5.0.8 on 2024-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_forbirthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(choices=[('TEMPORARILY_YEAR', 'Год'), ('TEMPORARILY_MONTH', 'Месяц'), ('TEMPORARILY_WEEK', 'Неделя')], max_length=300, verbose_name='Тип подписки')),
                ('used', models.BigIntegerField(default=1, verbose_name='Количество использования')),
                ('secret_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Секретный код')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
