# Generated by Django 5.0.8 on 2024-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_startbonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startbonus',
            name='secret_code',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Ссылка для копирования'),
        ),
    ]
