# Generated by Django 5.0.8 on 2024-11-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_startbonus_secret_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startbonus',
            options={'verbose_name': 'Бонусная ссылка', 'verbose_name_plural': 'Бонусные ссылки'},
        ),
        migrations.AlterField(
            model_name='startbonus',
            name='secret_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ссылка для копирования'),
        ),
    ]
