# Generated by Django 5.0.8 on 2024-11-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_startbonus_secret_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='startbonus',
            name='used_by',
            field=models.JSONField(default=list, verbose_name='Пользователи которые уже пользователи'),
        ),
    ]
