# Generated by Django 5.0.8 on 2024-11-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_startbonus_used_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartBonusSerail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BigIntegerField(default=1, verbose_name='Количество использования')),
                ('secret_code', models.CharField(blank=True, default='Generating', max_length=100, verbose_name='Ссылка для копирования')),
                ('used_by', models.JSONField(default=list, verbose_name='Пользователи которые уже пользователи')),
                ('serail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.serail')),
            ],
            options={
                'verbose_name': 'Бонусная ссылка сериалов',
                'verbose_name_plural': 'Бонусные ссылки сериалов',
            },
        ),
    ]
