# Generated by Django 5.0.8 on 2024-11-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_serieslikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serail',
            name='description',
            field=models.TextField(blank=True, default='For example', null=True, verbose_name='Описание'),
        ),
    ]
