# Generated by Django 5.0.8 on 2024-12-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_serail_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, null=True, verbose_name='Номер заказа')),
                ('status', models.CharField(blank=True, choices=[('TEMPORARILY_YEAR', 'TEMPORARILY_YEAR'), ('TEMPORARILY_MONTH', 'TEMPORARILY_MONTH'), ('TEMPORARILY_WEEK', 'TEMPORARILY_WEEK'), ('ALWAYS', 'ALWAYS'), ('ONCE', 'ONCE')], max_length=250, null=True, verbose_name='Тип')),
                ('serail_id', models.BigIntegerField(blank=True, null=True, verbose_name='Номер сериала')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
