# Generated by Django 5.0.8 on 2024-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='summa',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Сумма оплаты'),
        ),
    ]
