# Generated by Django 5.0.8 on 2024-12-06 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_orders_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
