# Generated by Django 5.0.6 on 2024-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_orders_delivered_remove_orders_delivereddone'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cooked',
            field=models.BooleanField(default=False, verbose_name='Говто'),
        ),
    ]
